(in-package #:fact-base)

(defparameter fb (make-fact-base :indices '(:a :ab :abc)))
(insert! (list 2 :whiskey :foxtrot) fb)
(insert! (list 1 :foxtrot :beta) fb)
(insert! (list 0 :whiskey :tango) fb)
(insert! (list 4 :tango :beta) fb)
(insert! (list 0 :b :c) fb)
(show (index fb))
(lookup fb :a 0)
(lookup fb :a 0 :b :whiskey)
(delete! (list 0 :whiskey :tango) fb)
(show (index fb))
(delete! (list 0 :b :c) fb)
(show (index fb))
