(in-package #:fact-base)

(defparameter fb (make-fact-base :indices '(:a :ab :abc)))
(insert! fb (list 2 :whiskey :foxtrot))
(insert! fb (list 1 :foxtrot :beta))
(insert! fb (list 0 :whiskey :tango))
(insert! fb (list 4 :tango :beta))
(insert! fb (list 0 :b :c))
(show (index fb))
(lookup fb :a 0)
(lookup fb :a 0 :b :whiskey)
(delete! fb (list 0 :whiskey :tango))
(show (index fb))
(delete! fb (list 0 :b :c))
(show (index fb))
